spring:
  application:
    name: 1build-ui

onebuild:
  ui:
    component:
      path: /app/components
      source-path: /app/modules
      list:
        datasource:
          home: /datasource
        version:
          home: /version

    store:
      path: /app/stores
      source-path: /app/stores

    index:
      main-component: version