spring:
  application:
    name: 1build-ui

onebuild:
  ui:
    main-component: datasource

  app:
    components:
      resource-type: COMPONENT
      path: /app/components
      source-path: /app/modules
      list:
        - name: datasource
          home: /datasource

    stores:
      resource-type: STORE
      path: /app/stores
      source-path: /app/stores

    services:
      resource-type: SERVICE
      path: /app/services
      source-path: /app/services

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.web.servlet: DEBUG
