spring:
  application:
    name: 1build-ui

onebuild:
  ui:
    main-component: datasource

  app:
    components:
      resource-type: COMPONENT
      web-path: /app/components
      source-path: /app/modules
      list:
      - name: datasource
        home: /datasource

    stores:
      resource-type: STORE
      web-path: /app/stores
      source-path: /app/stores
      list:

    services:
      resource-type: SERVICE
      web-path: /app/services
      source-path: /app/services
      list:

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.web.servlet: DEBUG
